import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientOnly from "./clientOnly";
import { Toaster } from "sonner";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import QueryProvider from "./provider/QueryClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient=new QueryClient()

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <QueryProvider>

        <ClientOnly>
  <main className="min-h-screen"> {children}</main>
        <Toaster richColors/>
        </ClientOnly>
     </QueryProvider>
      </body>
      
    </html>
  );
}
